"""
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis consectetur ipsum. Praesent sagittis sodales egestas. Nullam in rhoncus dolor, sed eleifend sapien. Ut mattis metus a lorem egestas dictum. Nullam egestas justo nulla, ac bibendum diam pharetra ac. Nulla convallis metus ac viverra porta. Donec rhoncus turpis vel sem lacinia maximus. In tincidunt venenatis mi. Maecenas in metus neque. Quisque dolor leo, euismod et lectus ut, volutpat ullamcorper nisl.

Ut a arcu nibh. Suspendisse volutpat ipsum at nulla auctor bibendum. Proin lobortis sed neque eu elementum. Proin sit amet iaculis lectus. Nam diam neque, suscipit id eros vitae, porta tincidunt diam. Maecenas ut sapien ac sapien laoreet lobortis. Praesent sagittis dolor auctor ullamcorper elementum. Quisque sit amet sem aliquet, lacinia nunc lacinia, suscipit est. Nunc metus nisl, accumsan quis nunc eu, dapibus varius ipsum. Phasellus efficitur accumsan metus, nec imperdiet nisl mollis non. Curabitur id diam et arcu faucibus tincidunt. Aenean ut justo eget ipsum varius sodales quis et quam. Nulla volutpat laoreet justo non condimentum. Nam scelerisque magna libero, at vehicula enim mattis sit amet. Aenean at neque nunc.

Quisque dui diam, porttitor at nisl sit amet, consequat scelerisque nulla. Mauris hendrerit leo a risus tempus euismod. Vivamus sapien purus, dignissim at augue sit amet, vestibulum pulvinar massa. Aenean in enim dictum, pharetra lorem sit amet, efficitur ex. Morbi sed quam mattis eros lobortis egestas. Cras finibus condimentum dolor, ut rutrum velit ultrices sit amet. Aliquam nibh dui, porta sit amet dapibus et, fermentum eu metus. Praesent semper sem tincidunt lacus facilisis, et placerat mauris porta.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec suscipit tristique purus tempor tempus. Proin sed nisl sem. Proin id facilisis est. Duis condimentum non nibh quis pharetra. Nam blandit auctor diam luctus ullamcorper. Integer sit amet urna sit amet nunc efficitur semper. Cras eget est non tellus rutrum elementum. Aliquam erat volutpat. Mauris tincidunt vehicula lacinia. Ut posuere est vel malesuada malesuada. Fusce laoreet lacus non auctor pretium. Fusce malesuada tempor mi ullamcorper cursus.

Nunc maximus purus et tellus convallis, eget accumsan massa finibus. Maecenas sed feugiat sapien. Quisque feugiat odio magna, suscipit vulputate nisi ultricies eu. Quisque suscipit tincidunt pretium. Morbi eu tempor quam. Aliquam ac velit a tellus maximus aliquet at et metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum volutpat dolor a diam hendrerit, mattis dapibus erat rhoncus. Quisque a bibendum dui, id fermentum mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur non enim pharetra, sagittis erat id, suscipit metus. Nulla quam massa, tempor sit amet pellentesque at, luctus non turpis. Sed quam nisl, tempus a maximus ac, efficitur vitae quam.

Suspendisse aliquet justo et est rhoncus ornare. Phasellus mollis ipsum scelerisque, gravida odio ut, sagittis lorem. Morbi non aliquet urna, id pellentesque odio. Duis auctor id ex id ultricies. Nullam odio odio, ullamcorper eu sem luctus, interdum vehicula est. In eleifend turpis sed nulla efficitur, et eleifend ipsum commodo. Donec faucibus velit sed felis ornare, a tincidunt mauris sagittis. Sed finibus malesuada libero eu lacinia. Curabitur porta tempor elit, laoreet semper dui faucibus ut. Fusce quis luctus mi. Vestibulum ut metus eget leo porttitor euismod.

Mauris et lacinia ligula. Fusce dolor ligula, gravida vel mi et, facilisis viverra ligula. Fusce tincidunt interdum turpis et vulputate. Pellentesque nec quam vel mi pharetra interdum sed vel magna. Proin luctus tortor sit amet pellentesque porta. Praesent quis justo efficitur, vulputate metus eget, tincidunt est. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi odio mauris, faucibus id porttitor quis, vulputate in justo. Nullam accumsan elit vel nibh pharetra, posuere aliquam est fermentum. Sed non libero odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam luctus vel lorem eu iaculis. Suspendisse tempus vehicula turpis in ullamcorper. Cras non libero ligula. Proin nec elementum elit. Mauris in diam id dui placerat convallis eu vitae purus.

Proin vulputate pellentesque gravida. Nullam eu justo in turpis tempus semper. Morbi nulla velit, pharetra quis neque nec, finibus maximus turpis. Sed scelerisque lacus id arcu fermentum pellentesque. Morbi luctus varius dolor et porta. Phasellus sed magna interdum, scelerisque odio sit amet, vestibulum turpis. Mauris faucibus orci lectus, quis pretium ex semper vel. Donec turpis velit, rhoncus quis lacinia ac, iaculis sollicitudin mi. Sed dictum eu enim in laoreet. Quisque mattis dictum tristique. Nullam ac mi accumsan, rutrum orci scelerisque, congue turpis.

In pharetra est sit amet neque porta, id interdum leo pulvinar. Suspendisse sollicitudin eleifend aliquam. Vestibulum condimentum luctus ipsum, at tincidunt nisi sollicitudin quis. Etiam non tellus ut ex fringilla lacinia. Nunc hendrerit leo vel vehicula vulputate. Etiam ultrices rhoncus dui, ut porta risus bibendum vitae. Pellentesque erat augue, vestibulum nec laoreet quis, sodales id quam. Sed in tempor odio. Quisque id nulla at tellus aliquet pretium. Quisque eu ullamcorper velit. Donec dignissim dignissim condimentum. Vestibulum egestas turpis vitae ex cursus, in ornare odio cursus.

Vestibulum porttitor suscipit odio ac maximus. Vivamus erat mauris, tristique ac cursus id, rutrum nec odio. Maecenas tempus urna ut sem porta convallis. Pellentesque accumsan magna a sem bibendum, eu efficitur odio pulvinar. Duis vel risus leo. Nam maximus nibh nec ligula sodales congue. Suspendisse et ultricies felis, quis scelerisque felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse vulputate urna in odio pretium maximus. Phasellus tempor porta pellentesque. Mauris arcu augue, sodales a vulputate nec, laoreet non leo. Vestibulum ultrices ullamcorper ullamcorper. Suspendisse placerat nibh ligula, at pulvinar ligula pharetra eget. Vivamus varius libero quis sapien posuere tristique.

Aliquam nec nibh elementum felis venenatis dignissim. Etiam at maximus nisl. Fusce sed nisl dapibus, lacinia felis eu, efficitur felis. Phasellus nunc velit, auctor eget laoreet at, euismod sagittis augue. In dignissim tortor in nibh vulputate fringilla. Mauris faucibus lectus in lectus viverra eleifend. Proin ex purus, maximus at efficitur in, faucibus et nulla. Donec id finibus diam. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Suspendisse et posuere ipsum. In lacinia bibendum magna, id faucibus sapien interdum id. Nullam fermentum, enim rutrum egestas porttitor, ex odio sodales massa, ut consequat purus odio id dolor.

Integer non lorem ac quam volutpat dictum a viverra odio. Nullam maximus arcu eget consequat rutrum. Phasellus nisl enim, lobortis vel augue condimentum, auctor dapibus metus. Fusce consequat vitae dolor eget accumsan. Sed non sollicitudin sem. Vestibulum nec elit ornare, bibendum elit in, hendrerit sapien. Nulla nec laoreet magna. Donec ac ante ornare lacus pretium consectetur hendrerit id neque. Phasellus vulputate, odio et tristique consectetur, felis arcu pellentesque nibh, vel mattis diam diam sit amet leo. Nulla nec consectetur erat. Maecenas ac sem quis nibh finibus venenatis sit amet sit amet est. Nam interdum urna pretium, semper quam nec, tempus odio. In tempus vulputate sapien a sodales.

Proin vitae neque vel nibh hendrerit tincidunt eget vel lacus. Mauris cursus maximus purus quis tincidunt. Mauris leo urna, faucibus at iaculis vitae, ullamcorper non erat. Vestibulum a porta magna. Donec posuere tellus at suscipit pretium. Fusce et dictum lectus. Morbi et diam non velit lacinia pretium vel nec orci. Proin non nulla a turpis congue scelerisque. Mauris sapien risus, viverra egestas nunc id, laoreet ultrices nunc. Aliquam enim dolor, pellentesque pharetra ornare vel, viverra at neque. Sed commodo vulputate luctus. Sed vel mauris libero. Nam mattis tincidunt neque, vitae placerat arcu elementum id.

Mauris dapibus, tortor sed maximus cursus, metus lectus blandit augue, eget dictum lectus enim nec leo. Suspendisse potenti. Pellentesque eu magna ultricies, scelerisque odio sit amet, viverra velit. Quisque sed justo quis elit ultrices semper. Pellentesque dapibus justo vitae risus hendrerit, ac mollis neque ultricies. In ullamcorper aliquam mi, eget tempor mauris imperdiet ac. Proin at quam nulla.

Mauris et eros ligula. Integer volutpat nisi sit amet consequat cursus. Curabitur dignissim nisi nulla, sed accumsan elit malesuada euismod. Suspendisse tellus metus, semper id mollis ac, viverra vel tortor. Pellentesque tincidunt mi felis, eu semper odio sollicitudin eu. Mauris vulputate mauris varius felis ornare luctus. Quisque fermentum pellentesque ligula vitae tristique. Suspendisse pretium quam dolor, nec tempus nibh pulvinar quis. Aliquam quis nunc facilisis, viverra velit ac, mattis diam. Vivamus suscipit, risus sed tempus mollis, sapien nibh viverra nisl, eget fermentum mi velit a tellus. Pellentesque maximus suscipit eros, sed egestas dui finibus sed. Etiam vestibulum eu quam et ultrices.

Duis mollis ornare massa, eu lacinia ante lacinia ut. Mauris viverra orci id facilisis accumsan. Phasellus tempus mi eget dui gravida condimentum. Cras fringilla luctus sagittis. Nullam malesuada scelerisque arcu, interdum finibus enim faucibus quis. Morbi iaculis ipsum arcu, eu tempus sem ullamcorper sit amet. Donec nibh quam, ornare pellentesque ipsum sed, pretium efficitur nulla. Quisque tempus dui at arcu dapibus consequat. Quisque in purus id turpis cursus pulvinar. Integer nisi metus, auctor ut enim vitae, faucibus elementum odio. Etiam luctus sapien ac egestas pulvinar. Etiam ultrices, justo aliquam scelerisque posuere, dolor erat elementum est, a malesuada purus libero ac quam. Nullam et nulla dui. Vivamus leo quam, suscipit id vehicula et, molestie porta metus. Morbi mi purus, volutpat ut quam id, faucibus vestibulum metus. Nulla non dictum diam amet.

"""

from citrus import *

gfx.init_default()
console.init(gfx.SCREEN_TOP)

print('hello!')

while apt.main_loop():
    hid.scan_input()
    if hid.keys_down() & hid.KEY_START:
        break
    gfx.flush_buffers()
    gfx.swap_buffers()
    gsp.wait_for_vblank()

gfx.exit()
